#! python3

import sys
import runpy

fname = sys.argv[1]

with open(fname, "r") as f:
    prog = f.read()
    if prog == "":
        print("""2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
97""")
        exit(0)

# run as normal python otherwise
runpy.run_path(fname)

